export type ComponentType =
  | 'NInput'
  | 'NInputNumber'
  | 'NSelect'
  | 'NTreeSelect'
  | 'NRadio'
  | 'NRadioGroup'
  | 'NCheckbox'
  | 'NAutoComplete'
  | 'NCascader'
  | 'NDatePicker'
  | 'NTimePicker'
  | 'NSwitch'
  | 'NUpload'
  | 'NSlider'
  | 'NRate';
